1) HANDLE EXCEPTION IN NUMBER:

import java.util.*;

 class Main {

	public static void main(String[] args) {
		Scanner s = new Scanner(System.in);
		
		System.out.print("Enter an integer: ");
		String s1 = s.nextLine();
		
		try {
			int i = Integer.parseInt(s1);
			System.out.println("The square value is: " + i * i);
			System.out.println("The work has been done successfully");
		} catch (NumberFormatException e) {
			System.out.println("Entered input is not a valid format for an integer.");
		
		}
		
		s.close();

	}

}


2)ACCESSING ELEMENT:

import java.util.*;

 class Main {

	public static void main(String[] args) {
		Scanner s = new Scanner(System.in);
		
		System.out.print("Enter the size of array: ");
		int n = s.nextInt();
		
		int[] a = new int[n];
		
		System.out.println("Enter the elements to be present in array: ");
		for (int i = 0; i < n; i++)
			a[i] = s.nextInt();
		
		System.out.println("Enter the index of the array element you want to access");
		int index = s.nextInt();
		try {
			System.out.println("The array element at index " + index + " = " + a[index]);
			System.out.println("The array element successfully accessed");
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("java.lang.ArrayIndexOutOfBoundsException");
		}

		s.close();
	}

}

3)

import java.util.*;

 class Main {

	public static void main(String[] args) {
		Scanner s = new Scanner(System.in);
		
		System.out.print("Enter the size of array: ");
		int n = s.nextInt();
		
		int[] a = new int[n];
		
		System.out.println("Enter the elements to be present in array: ");
		try {
			for (int i = 0; i < n; i++)
				a[i] = s.nextInt();
		
			System.out.println("Enter the index of the array element that you want to access");

			int index = s.nextInt();
			System.out.println("The array element at index " + index + " = " + a[index]);
			System.out.println("The array element successfully accessed");
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("java.lang.ArrayIndexOutOfBoundsException");
		} catch (InputMismatchException e) {
			System.out.println("java.util.InputMismatchException");
		}

		s.close();

	}

}

4)

import java.util.*;

 class Main {

	public static void main(String[] args) {
		int n = args.length;
		
		for (int i = 0; i < n; i++)
			if (args[i].charAt(args[i].length() - 1) == ',') 
				args[i] = args[i].replace(",", "");
		
		
		
		int[] a = new int[n];

		int sum = 0;
		double avg = 0;
		
		try {
			for (int i = 0; i < n; i++)
				a[i] = Integer.parseInt(args[i]);
			
			for (int i = 0; i < n; i++)
				sum =sum + a[i];
			
			avg = sum / n;
		} catch (NumberFormatException e) {
			System.out.println("NumberFormatException");
		} catch (ArithmeticException e) {
			System.out.println("ArithmeticException");
		} catch (InputMismatchException e) {
			System.out.println("InputMismatchException");
		}
		
		System.out.println("sum: " + sum);
		System.out.println("avg: " + avg);
		
	}

}

5)DIVISION METHOD:
import java.util.*;

 class Main {

	public static void main(String[] args) {
		Scanner s = new Scanner(System.in);
		
		int a = s.nextInt();
		int b = s.nextInt();
		
		try {
			double r = division(a, b);
			System.out.println(r);
		} catch (ArithmeticException e) {
			System.out.println(e.getMessage());
		}
		
		s.close();
	}
	
	public static double division(int a, int b) throws ArithmeticException {
		return a / b;
	}

}

6)
import java.util.*;

 class Main {

	public static void main(String[] args) {
		Scanner s = new Scanner(System.in);
		
		for (int i = 0; i < 2; i++) {
			String name = "";
			int subA = 0;
			int subB = 0;
			int subC = 0;
			
			try {				
				name = s.nextLine();
				
				if (s.hasNextInt())
					subA = s.nextInt();
				else
					throw new NumberFormatException();
				
				if (s.hasNextInt())
					subB = s.nextInt();
				else
					throw new NumberFormatException();
				
				if (s.hasNextInt())
					subC = s.nextInt();
				else
					throw new NumberFormatException();
				
				if (subA < 0) throw new NegativeValuesException();
				if (subA > 100) throw new ValuesOutOfRangeException();
				
				if (subB < 0) throw new NegativeValuesException();
				if (subB > 100) throw new ValuesOutOfRangeException();
				
				if (subC < 0) throw new NegativeValuesException();
				if (subC > 100) throw new ValuesOutOfRangeException();
				
				
			} catch (ArithmeticException e) {
				System.out.println(e.getMessage());
			} catch (NegativeValuesException e) {
				System.out.println(e.getMessage());
			} catch (ValuesOutOfRangeException e) {
				System.out.println(e.getMessage());
			}
			
			System.out.println("Name: " + name);
			System.out.println("Marks of subject A: " + subA);
			System.out.println("Marks of subject B: " + subB);
			System.out.println("Marks of subject C: " + subC);
		}
		
		s.close();

	}

}

public class NegativeValuesException extends Exception {
	public NegativeValuesException() {
		super();
		System.out.println("NegativeValuesException occured");
	}
}
public class ValuesOutOfRangeException extends Exception {
	public ValuesOutOfRangeException() {
		super();
		System.out.println("ValuesOutOfRangeException occured");
	}
}

8)
import java.util.*;

 class Main {

	
		public static void main(String[] args) throws InvalidAgeException {
		String n = args[0];
		
		int age = Integer.parseInt(args[1]);
		
		if (age < 18 || age >= 60)
			throw new InvalidAgeException();
		
		System.out.println("Name: " + n + " Age: " + age);
	}

}
public class InvalidAgeException extends Exception {
	public InvalidAgeException() {
		super();
		System.out.println("Invalid age");
	}
}

9)
import java.util.*;

 class Main {

	
		public static void main(String[] args) throws InvalidAgeException
    Scanner s = new Scanner(System.in);
		
		try {
			System.out.println("Enter the 2 numbers");
			int a = s.nextInt();
			int b = s.nextInt();
			int q = a / b;
			System.out.println("The quotient of " + a + " / " + b + " = " + q);
		} catch (ArithmeticException e) {
			System.out.println(e.getMessage() + " caught");
		} finally {
			System.out.println("Inside finally block");
		}

		s.close();
	}

}
